---
roles:
  - name: geerlingguy.nginx
    version: 2.8.0

  - name: geerlingguy.memcached
    version: 1.1.0

  - name: geerlingguy.certbot
    version: 3.1.0

  - name: geerlingguy.htpasswd
    version: 2.0.0

collections:
  - name: ansible.posix
    version: 1.2.0
