---
- hosts: static

  become: yes

  vars_files:
    - vars/subsite-static.yml

  roles:
    - geerlingguy.nginx

  post_tasks:
    - name: copy static site files
      ansible.posix.synchronize:
        src: "{{ static_site_files }}"
        dest: "{{ server_root }}"
        recursive: yes
        times: yes
        delete: yes

    - name: set static site permissions
      ansible.builtin.file:
        path: "{{ server_root }}"
        owner: "{{ nginx_user }}"
        group: "{{ nginx_user }}"
        recurse: yes
